### ISSUE TITLE
Notebooks missing

### ISSUE THREAD

**Issue by charles-mahaco** [deep-and-shallow/notebooks#1]
Hi,

I just received the book but noticed the notebooks are not uploaded yet. Do you know when they will be?
Thanks!

**Comment by deep-and-shallow** [comment]
Hello Charles, thanks for your email.
We are porting the notebooks over from a past repository, and they will be
available at this repository early next week.
Thank you,
Ross

**Comment by charles-mahaco** [comment]
Ok, thank you!
